version: "3.7"
services:
  backend:
    container_name: backend
    build: ./pokedex-backend
    ports:
      - "5000:5000"
    networks:
      - overlay
    depends_on:
      - mongo
    environment: 
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_POKEMON=pokemons-db
  mongo:
    container_name: mongo
    image: mongo:4.2.2-bionic
    volumes:
      - db-data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    # command: 
      # - mongoimport -d pokemons-db -c pokemons --type json --file /docker-entrypoint-initdb.d/pokedex.json --jsonArray 
    networks:
      - overlay



volumes:
  db-data:

networks:
  overlay: